# ---------------------------
#
# Check the source files for quality issues
#
# ---------------------------

name: Lint

on:
  push:
    branches:
      - main
      - master
      - release/**
  pull_request:
    branches:
      - main
      - master
      - release/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ruff:
    name: ruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: astral-sh/ruff-action@v3
        with:
          # don't error (yet)
          args: "check --exit-zero"
