# -----------------------
#
# Run the test suite from the git repo
# using uv to install all dependencies.
#
# -----------------------

name: Python test

on:
  push:
    branches:
      - main
      - master
      - release/**
  pull_request:
    branches:
      - main
      - master
      - release/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Python ${{ matrix.python-version }} (${{ matrix.os }})

    strategy:
      fail-fast: false
      matrix:
        os:
          - macOS
          - Ubuntu
          - Windows
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
    runs-on: ${{ matrix.os }}-latest

    steps:
      - name: Get source code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Package list
        run: uv pip list

      - name: Run pytest suite
        run: uv run pytest --cov pycondor --junitxml=pytest.xml --pyargs pycondor -ra -v

      - name: Coverage report
        run: uv run -m coverage report --show-missing

      - name: Prepare codecov upload
        run: uv run -m coverage xml

      - name: Publish coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage.xml
          flags: ${{ runner.os }},python${{ matrix.python-version }}

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: pytest-${{ matrix.os }}-${{ matrix.python-version }}
          path: pytest.xml
